import React, { useState, useRef, useEffect } from 'react';
import { UploadIcon, MagicWandIcon, DownloadIcon, CameraIcon, RefreshIcon } from './components/IconComponents';
import PreviewRenderer from './components/PreviewRenderer';
import { transcribeHandwriting, generateCreativeTitles } from './services/geminiService';
import { saveToHistory, getHistory, deleteFromHistory } from './services/historyService';
import { DocumentContent, ThemeType, ProcessingState, TitleSuggestion, ThemeCategory, AspectRatio } from './types';
import { THEMES } from './constants';

const App = () => {
  // --- State ---
  const [step, setStep] = useState<'upload' | 'edit' | 'preview'>('upload');
  
  const [content, setContent] = useState<DocumentContent>({
    title: '',
    subtitle: '',
    author: '',
    body: '',
  });

  const [processing, setProcessing] = useState<ProcessingState>({
    isAnalyzing: false,
    isGenerativeTitles: false,
    progressMessage: '',
  });

  const [suggestions, setSuggestions] = useState<TitleSuggestion[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  
  const [activeTheme, setActiveTheme] = useState<ThemeType>(ThemeType.MODERN_MEMO);
  const [activeCategory, setActiveCategory] = useState<ThemeCategory>(ThemeCategory.ESSENTIAL);
  // Default to 3:4 as requested
  const [aspectRatio, setAspectRatio] = useState<AspectRatio>('3:4');
  const [historyItems, setHistoryItems] = useState<DocumentContent[]>([]);
  
  // Random Seed for Generative Features
  const [randomSeed, setRandomSeed] = useState<number>(Date.now());

  const fileInputRef = useRef<HTMLInputElement>(null);

  // Load history on mount
  useEffect(() => {
    setHistoryItems(getHistory());
  }, []);

  // Save to history when entering edit or preview
  useEffect(() => {
    if ((step === 'edit' || step === 'preview') && content.body) {
      const saved = saveToHistory(content);
      // Update the local content with the ID generated by history service
      if (!content.id) {
         setContent(saved);
      }
    }
  }, [step, content.title, content.body]);

  // --- Handlers ---

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setProcessing({ isAnalyzing: true, isGenerativeTitles: false, progressMessage: 'Scanning document...' });
    
    try {
      // 1. OCR Step
      const extractedContent = await transcribeHandwriting(file);
      setContent(extractedContent);

      // 2. Recommendation Logic (New)
      recommendTheme(extractedContent);

      // 3. Auto-Enhance Step if title missing
      if (!extractedContent.title) {
        setProcessing(prev => ({ ...prev, progressMessage: 'Analyzing context for titles...', isGenerativeTitles: true }));
        const generatedSuggestions = await generateCreativeTitles(extractedContent.body);
        setSuggestions(generatedSuggestions);
        setShowSuggestions(true);
      }

      setStep('edit');
    } catch (error) {
      alert('Failed to process image. Please try again.');
    } finally {
      setProcessing({ isAnalyzing: false, isGenerativeTitles: false, progressMessage: '' });
    }
  };

  const recommendTheme = (content: DocumentContent) => {
    const text = (content.body + " " + content.title).toLowerCase();
    
    // Priority 1: Midnight Mood
    if (text.match(/night|lonely|dream|dark|sleep|moon|star|深夜|夜晚|孤独/i)) {
        setActiveTheme(ThemeType.MIDNIGHT_MOOD);
        setActiveCategory(ThemeCategory.SOCIAL);
        return;
    }

    // Priority 2: Warm Memo
    if (text.match(/review|diary|journal|date|monday|tuesday|wednesday|thursday|friday|saturday|sunday|复盘|日记|总结/i)) {
        setActiveTheme(ThemeType.WARM_MEMO);
        setActiveCategory(ThemeCategory.SOCIAL);
        return;
    }

    // Priority 3: Clear Grid (Short & Light)
    if (content.body.length < 100 && text.match(/simple|light|soft|cloud|治愈/i)) {
        setActiveTheme(ThemeType.CLEAR_GRID);
        setActiveCategory(ThemeCategory.SOCIAL);
        return;
    }

     // Priority 4: Illustration (Pet/Dessert vibe)
     if (text.match(/cat|dog|coffee|tea|cake|pet|love|cute|猫|狗|咖啡|甜点/i)) {
        setActiveTheme(ThemeType.MINIMAL_ILLUSTRATION);
        setActiveCategory(ThemeCategory.SOCIAL);
        return;
    }
    
    // Default fallback (no change or stay on current default)
  };

  const handleHistorySelect = (item: DocumentContent) => {
    setContent(item);
    setStep('edit');
  };

  const handleDeleteHistory = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    deleteFromHistory(id);
    setHistoryItems(getHistory());
  };

  const handleManualTitleGen = async () => {
    if (!content.body) return;
    setProcessing({ isAnalyzing: false, isGenerativeTitles: true, progressMessage: 'Dreaming up titles...' });
    try {
      const generatedSuggestions = await generateCreativeTitles(content.body);
      setSuggestions(generatedSuggestions);
      setShowSuggestions(true);
    } catch (e) {
      alert('Could not generate titles.');
    } finally {
      setProcessing(prev => ({ ...prev, isGenerativeTitles: false, progressMessage: '' }));
    }
  };

  const applySuggestion = (s: TitleSuggestion) => {
    setContent(prev => ({ ...prev, title: s.title, subtitle: s.subtitle }));
    setShowSuggestions(false);
  };

  const handlePrint = () => {
    window.print();
  };

  const regenerateSeed = () => {
    setRandomSeed(Date.now());
  };

  const handleSurpriseMe = () => {
     setActiveTheme(ThemeType.SURPRISE_ME);
     regenerateSeed();
  };

  // --- UI Components ---

  const renderUploadStep = () => (
    <div className="flex flex-col md:flex-row h-screen">
      {/* Upload Area */}
      <div className="flex-1 flex flex-col items-center justify-center p-8 bg-gray-50">
        <div className="bg-white p-10 rounded-2xl shadow-xl border border-gray-100 max-w-md w-full text-center">
            <div className="w-16 h-16 bg-blue-50 text-blue-600 rounded-full flex items-center justify-center mx-auto mb-6">
            <UploadIcon />
            </div>
            <h2 className="text-2xl font-bold text-slate-800 mb-2">Digitize Your Handwriting</h2>
            <p className="text-slate-500 mb-8">Upload a photo. We'll format it professionally.</p>
            
            <div className="space-y-4">
                <button 
                onClick={() => fileInputRef.current?.click()}
                className="w-full py-3 px-4 bg-slate-900 hover:bg-slate-800 text-white rounded-lg font-medium transition-colors flex items-center justify-center gap-2"
                disabled={processing.isAnalyzing}
                >
                {processing.isAnalyzing ? (
                    <span className="animate-pulse">Processing...</span>
                ) : (
                    <>
                    <UploadIcon />
                    <span>Select Image</span>
                    </>
                )}
                </button>
                <input 
                type="file" 
                ref={fileInputRef} 
                className="hidden" 
                accept="image/*"
                onChange={handleFileUpload}
                />
            </div>

            {processing.isAnalyzing && (
            <div className="mt-6">
                <div className="w-full bg-gray-200 rounded-full h-1.5 mb-2">
                <div className="bg-blue-600 h-1.5 rounded-full animate-[width_2s_ease-in-out_infinite]" style={{width: '60%'}}></div>
                </div>
                <p className="text-xs text-slate-400">{processing.progressMessage}</p>
            </div>
            )}
        </div>
      </div>

      {/* History Sidebar */}
      <div className="w-full md:w-80 bg-white border-l border-gray-200 overflow-y-auto p-6">
         <h3 className="font-bold text-slate-800 mb-6 flex items-center gap-2">
            <span className="w-2 h-2 bg-green-500 rounded-full"></span>
            Recent Drafts
         </h3>
         {historyItems.length === 0 ? (
            <p className="text-slate-400 text-sm text-center mt-10">No history yet.</p>
         ) : (
            <div className="space-y-3">
                {historyItems.map((item) => (
                    <div 
                        key={item.id} 
                        onClick={() => handleHistorySelect(item)}
                        className="p-4 rounded-xl border border-gray-100 hover:border-blue-200 hover:bg-blue-50 transition-all cursor-pointer group relative"
                    >
                        <h4 className="font-bold text-slate-700 text-sm truncate mb-1">{item.title || 'Untitled Draft'}</h4>
                        <p className="text-xs text-slate-400 truncate">{item.body.substring(0, 40)}...</p>
                        <p className="text-[10px] text-slate-300 mt-2">
                           {item.lastModified ? new Date(item.lastModified).toLocaleDateString() : ''}
                        </p>
                        <button 
                           onClick={(e) => item.id && handleDeleteHistory(e, item.id)}
                           className="absolute top-2 right-2 p-1 text-gray-300 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                        >
                            &times;
                        </button>
                    </div>
                ))}
            </div>
         )}
      </div>
    </div>
  );

  const renderEditorStep = () => (
    <div className="grid lg:grid-cols-2 gap-0 h-screen overflow-hidden">
      {/* Left: Editor */}
      <div className="flex flex-col h-full bg-white border-r border-gray-200 shadow-xl z-10 overflow-y-auto">
        <div className="p-6 md:p-8 flex-1">
           <div className="flex justify-between items-center mb-8">
             <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
               <span className="w-2 h-6 bg-blue-600 rounded-full"></span>
               Edit Content
             </h3>
             <button 
                onClick={() => setStep('preview')}
                className="text-sm font-semibold text-blue-600 hover:text-blue-700 flex items-center gap-1"
             >
               Next: Style &rarr;
             </button>
           </div>

           <div className="space-y-6">
              {/* Title Section */}
              <div className="relative">
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Title</label>
                <div className="flex gap-2">
                  <input 
                    type="text" 
                    value={content.title}
                    onChange={(e) => setContent({...content, title: e.target.value})}
                    placeholder="Document Title"
                    // Added bg-white and text-slate-900 explicit colors
                    className="flex-1 p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all font-serif text-lg bg-white text-slate-900"
                  />
                  <button 
                    onClick={handleManualTitleGen}
                    disabled={processing.isGenerativeTitles}
                    className="p-3 bg-indigo-50 text-indigo-600 rounded-lg hover:bg-indigo-100 transition-colors"
                    title="Generate AI Titles"
                  >
                    {processing.isGenerativeTitles ? <RefreshIcon /> : <MagicWandIcon />}
                  </button>
                </div>

                {/* Suggestions Dropdown */}
                {showSuggestions && (
                  <div className="absolute top-full left-0 right-0 mt-2 bg-white border border-indigo-100 shadow-xl rounded-xl p-2 z-20 animate-in fade-in zoom-in-95 duration-200">
                    <div className="flex justify-between items-center px-2 py-1 mb-2 border-b border-gray-50">
                      <span className="text-xs font-bold text-indigo-500">AI Suggestions</span>
                      <button onClick={() => setShowSuggestions(false)} className="text-xs text-gray-400 hover:text-gray-600">Close</button>
                    </div>
                    <div className="space-y-2">
                      {suggestions.map((s, idx) => (
                        <button 
                          key={idx}
                          onClick={() => applySuggestion(s)}
                          className="w-full text-left p-3 hover:bg-indigo-50 rounded-lg group transition-all"
                        >
                          <div className="flex justify-between items-start">
                             <span className="font-semibold text-slate-800 text-sm">{s.title}</span>
                             <span className="text-[10px] uppercase tracking-wider bg-white border border-gray-200 px-1.5 py-0.5 rounded text-gray-500">{s.style}</span>
                          </div>
                          <p className="text-xs text-slate-500 mt-1 italic group-hover:text-indigo-600">{s.subtitle}</p>
                        </button>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Subtitle */}
              <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Subtitle / Quote</label>
                <input 
                    type="text" 
                    value={content.subtitle}
                    onChange={(e) => setContent({...content, subtitle: e.target.value})}
                    placeholder="A catchy subtitle or quote..."
                    className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-sm font-medium bg-white text-slate-900"
                />
              </div>

               {/* Author */}
               <div>
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Author</label>
                <input 
                    type="text" 
                    value={content.author}
                    onChange={(e) => setContent({...content, author: e.target.value})}
                    placeholder="Author Name"
                    className="w-full p-3 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-sm font-medium bg-white text-slate-900"
                />
              </div>

              {/* Body */}
              <div className="flex-1">
                <label className="block text-xs font-bold text-slate-400 uppercase tracking-wider mb-2">Content</label>
                <textarea 
                  value={content.body}
                  onChange={(e) => setContent({...content, body: e.target.value})}
                  className="w-full h-96 p-4 border border-gray-200 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none text-base leading-relaxed resize-none font-mono bg-white text-slate-900"
                  placeholder="Body content..."
                />
              </div>
           </div>
        </div>
      </div>

      {/* Right: Live Preview (Hidden on small mobile until step change) */}
      <div className="hidden lg:block bg-gray-100 p-8 overflow-y-auto h-full flex items-center justify-center">
         <div className="w-[500px] shadow-2xl origin-center transform scale-90">
            <PreviewRenderer content={content} theme={activeTheme} aspectRatio="3:4" seed={randomSeed} />
         </div>
      </div>
    </div>
  );

  const renderPreviewStep = () => (
    <div className="h-screen flex flex-col bg-slate-900">
      {/* Top Bar */}
      <div className="h-16 bg-slate-800 border-b border-slate-700 flex items-center justify-between px-6 shrink-0 z-20">
         <div className="flex items-center gap-4">
             <button 
               onClick={() => setStep('edit')}
               className="text-slate-300 hover:text-white text-sm flex items-center gap-2"
             >
               &larr; Back to Edit
             </button>

             {/* Surprise Me Button */}
             <button
               onClick={handleSurpriseMe}
               className="ml-4 bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white px-3 py-1.5 rounded-full text-xs font-bold flex items-center gap-2 shadow-lg animate-pulse"
             >
                <MagicWandIcon /> Surprise Me
             </button>
             
             {/* Regenerate Seed Button (for generative themes) */}
             <button
                onClick={regenerateSeed}
                className="bg-slate-700 hover:bg-slate-600 text-white p-2 rounded-full"
                title="Shuffle Random Elements"
             >
                <RefreshIcon />
             </button>
         </div>
         
         {/* Aspect Ratio Selector Removed as per request, fixed to 3:4 */}
         <div className="text-slate-400 text-xs font-mono">
            ASPECT: 3:4
         </div>

         <div className="flex items-center gap-4">
            <button 
              onClick={handlePrint}
              className="bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition-all"
            >
              <DownloadIcon /> Export / Print
            </button>
         </div>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Main Preview Area */}
        <div className="flex-1 bg-neutral-900 overflow-y-auto p-4 md:p-12 flex justify-center items-start print:p-0 print:bg-white print:overflow-visible relative">
           <div id="print-area" className={`w-full max-w-3xl shadow-2xl print:shadow-none print:w-full transition-all duration-300`}>
              <PreviewRenderer content={content} theme={activeTheme} aspectRatio={aspectRatio} seed={randomSeed} />
           </div>
        </div>

        {/* Theme Selector Sidebar */}
        <div className="w-80 bg-slate-800 border-l border-slate-700 flex flex-col print:hidden">
          {/* Categories Tab */}
          <div className="p-4 border-b border-slate-700 overflow-x-auto whitespace-nowrap">
              <div className="flex gap-2">
                  {Object.values(ThemeCategory).map(cat => (
                      <button 
                        key={cat}
                        onClick={() => setActiveCategory(cat)}
                        className={`px-3 py-1.5 rounded-full text-xs font-bold transition-colors ${
                            activeCategory === cat 
                            ? 'bg-white text-slate-900' 
                            : 'bg-slate-700 text-slate-400 hover:bg-slate-600'
                        }`}
                      >
                          {cat}
                      </button>
                  ))}
              </div>
          </div>

          {/* Theme List */}
          <div className="flex-1 overflow-y-auto p-6 space-y-4">
            {THEMES.filter(t => t.category === activeCategory).map(theme => (
               <button
                 key={theme.id}
                 onClick={() => setActiveTheme(theme.id)}
                 className={`w-full text-left p-4 rounded-xl border transition-all ${
                   activeTheme === theme.id 
                     ? 'border-blue-500 bg-slate-700 ring-1 ring-blue-500' 
                     : 'border-slate-600 hover:bg-slate-700/50 bg-slate-800'
                 }`}
               >
                 <div className="flex items-center gap-3 mb-2">
                    <div className={`w-4 h-4 rounded-full border border-gray-300 ${theme.previewColor}`}></div>
                    <span className="text-sm font-bold text-white">{theme.name}</span>
                 </div>
                 <p className="text-xs text-slate-400">{theme.description}</p>
               </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen font-sans bg-gray-50 text-slate-900">
      {step === 'upload' && renderUploadStep()}
      {step === 'edit' && renderEditorStep()}
      {step === 'preview' && renderPreviewStep()}
      
      {/* Print Styles */}
      <style>{`
        @media print {
          body * {
            visibility: hidden;
          }
          #print-area, #print-area * {
            visibility: visible;
          }
          #print-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
            height: auto;
            box-shadow: none;
            margin: 0;
            padding: 0;
          }
        }
      `}</style>
    </div>
  );
};

export default App;